<div id="adminEditor" class="full_w">
        <div class="h_title">Cambiar contrase&ntilde;a administrador</div>
                <div class="element" >
                <form action="/backend/adminp" method="post"><dl>
                        <div id="msga" class="element"><b><?php echo $this->msg;?></b></div>
                        <input type="hidden" name="admin_id" id="admin_id" value="<?php echo $this->id;?>" />
                        <div class="element">
                        <label>Nueva contrase&ntilde;a:</label><input type="password" name="admin_pass1" id="admin_pass1" /><text>(minimo 6 caracteres)</text><br><br>
                        <label>Repetir contrase&ntilde;a:</label><input type="password" name="admin_pass2" id="admin_pass2" />
                        </div>
                        <div class="entry">
                        <button>Guardar</button>
                        </div>
                </form> 
        </div>
      
</div>


