<!DOCTYPE html>
<html>
<head>
<title>Colabianchi</title>
<meta charset=utf-8 >

<meta name="robots" content="index, follow" > 
<meta name="keywords" content="" > 
<meta name="description" content="" > 
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="shortcut icon" href="favicon.ico">

<!-- CSS begin -->


<link rel="stylesheet" type="text/css" href="/css/style.css" >
<link rel="stylesheet" type="text/css" href="/css/skeleton.css" >

<link rel="stylesheet" type="text/css" href="/css/jquery.fancybox-1.3.4.css"  >
<link rel="stylesheet" href="/css/switcher/style.css">
<link rel="stylesheet" href="/css/layout/wide.css" id="layout">
<link rel="stylesheet" href="/css/colors/blue.css" id="colors">

<!--[if lte IE 8]><link rel="stylesheet" type="text/css" href="css/ie-warning.css" ><![endif]-->
<!--[if lte IE 8]><link rel="stylesheet" type="text/css" href="css/ei8fix.css" ><![endif]-->

<!-- flexslider slider CSS -->

<link rel="stylesheet" type="text/css" href="/css/flexslider.css"  >

	   <!--end flexslider slider CSS -->


<!-- CSS end -->

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<?php echo $this->headScript(); ?>

</head>
<body>

<div id="wrap" class="boxed">
<div class="grey-bg"> <!-- Grey bg  -->	


<!--[if lte IE 7]>
<div id="ie-container">
<div id="ie-cont-close">
<a href='#' onclick='javascript&#058;this.parentNode.parentNode.style.display="none"; return false;'><img src='/images/ie-warning-close.jpg' style='border: none;' alt='Close'></a>
</div>
<div id="ie-cont-content" >
<div id="ie-cont-warning">
<img src='/images/ie-warning.jpg' alt='Warning!'>
</div>
<div id="ie-cont-text" >
<div id="ie-text-bold">
You are using an outdated browser
</div>
<div id="ie-text">
For a better experience using this site, please upgrade to a modern web browser.
</div>
</div>
<div id="ie-cont-brows" >
<a href='http://www.firefox.com' target='_blank'><img src='/images/ie-warning-firefox.jpg' alt='Download Firefox'></a>
<a href='http://www.opera.com/download/' target='_blank'><img src='/images/ie-warning-opera.jpg' alt='Download Opera'></a>
<a href='http://www.apple.com/safari/download/' target='_blank'><img src='/images/ie-warning-safari.jpg' alt='Download Safari'></a>
<a href='http://www.google.com/chrome' target='_blank'><img src='/images/ie-warning-chrome.jpg' alt='Download Google Chrome'></a>
</div>
</div>
</div>
<![endif]-->

<!-- HEADER -->
<header id="header" >
<div class="container clearfix">
<div class="sixteen columns header-position">
<div class="header-container m-top-30 clearfix">

<div class="header-logo-container ">
<div class="logo-container">	
<a href="index.html" class="logo" rel="home" title="Home">
<img src="/images/logo.jpg" alt="Colabianchi" >
</a>
</div>
</div>

<div class="header-menu-container right">
<!-- TOP MENU -->
<nav id="main-nav">
<ul class="sf-menu clearfix">
	<li class="modulo" rel="inicio"><a href="/">Inicio</a>
		<ul>
			<li><a href="/index/novedades">Novedades</a></li>
	</ul>
	</li>
	<li class="modulo" rel="instituto"><a href="/index/staffifa">El instituto</a>
		<ul>
			<li><a href="/index/staffifa">Staff</a></li>
			<li><a href="/index/cifras">Cifras</a></li>
			<li><a href="/index/avantialab">Avantia Lab</a></li>
			<li><a href="/index/vinculos">Vinculos</a></li>
		</ul>
	</li>
	<li class="modulo" rel="servicios"><a href="/index/servicios">Servicios</a>
		<ul>
			<li><a href="/index/fertilidad">Fertilidad</a></li>
			<li><a href="/index/avantialab">Avantia Lab</a></li>
			<li><a href="/index/gineco">Ginecolog&iacute;a</a></li>
			<li><a href="/index/andrologia">Androlog&iacute;a</a></li>
			<li><a href="/index/endocrinologia">Endocrinolog&iacute;a</a></li>
			<li><a href="/index/pediatria">Pediatr&iacute;a</a></li>
		</ul>
	</li>
	<li class="modulo" rel="fertilidad"><a href="/index/fertilidad">Fertilidad</a></li>
	<li class="modulo" rel="avantialab"><a href="/index/avantialab">Avantia Lab</a></li>
	<li class="modulo" rel="contacto"><a href="/index/contacto">Contacto</a></li>
 </ul>
</nav>
<!--div class="search-container ">
<form action="#" class="search-form">
<input type="text" name="search-form-txt" class="search-text" >
<input type="submit" value="" class="search-submit" name="submit">
</form>
</div-->

</div>

</div>
</div>
</div>

</header>
<?php echo $this->layout()->content ?>

<?php echo $this->partial('index/partials/novedadesList.phtml',array('novedades'=>$this->novedadesnew)); ?>


<!-- NEWS LETTER -->
<div class="dark-grey-bg">
<div class="container m-bot-20 clearfix">
<div class="sixteen columns">
<div class="newsletter-container clearfix">
<div class="nl-img-container">
<img src="/images/icon-mail.png" alt="mail">
</div>
<div class="nl-text-container clearfix">
<div class="caption">
<span class="bold">NEWS</span> LETTER
</div>
<div class="nl-text">Suscr&iacute;base y lo mantendremos informado de las &uacute;ltimas novedades</div>
<div class="nl-form-container">
<form class="newsletterform" method="post" action="#" enctype="multipart/form-data" action="/index/guardarcon">
<input type="text" onblur="if(this.value=='')this.value='Su e-mail aquí...';" onfocus="if(this.value=='Su e-mail aquí...')this.value='';" value="Su e-mail aquí..." id="email" name="email"><input type="button" class="nl-button2" onclick="frontend.misc.news()" value="SUSCRIBIRME">
</form>
</div>	
</div>
</div>
</div>
</div>
</div>

<!-- OUR CLIENTS -->
<div class="container clearfix">
<div class="sixteen columns m-bot-20">
<ul class="our-clients-container clearfix ">
<li class="">
<a href="">
<div class="bw-wrapper">
<img src="/images/sisa.png" alt="client" >
</div>
</a>
</li>
<li class="">
<a href="">
<div class="bw-wrapper">
<img src="/images/ministerio.jpg" alt="client" >
</div>
</a>
</li>
<li class="last">
  El instituto de Fertilidad Asistida figura inscripto en el Registro Federal de Establecimientos de Salud del Sistema Integrado de Información Sanitaria Argentina, perteneciente al Ministerio de Salud de la Nación.
</li>
</ul>
</div>	
</div>

<!-- FOOTER -->
<footer>
<div class="footer-content-bg">
<div class="container clearfix">
<div class="one-third-footer-spec column omega">

<div class="logo-footer-container">	
<a href="index.html" class="logo" rel="home" title="Home">
<img src="/images/logo.jpg" alt="Colabianchi" >
</a>
</div>
</div>
<div class="two-thirds-footer-spec column alpha">


<p class="footer-content-container m-none">PRIORIZAMOS LA <strong>&Eacute;TICA PROFESIONAL</strong> Y EL <strong>RESPETO A LA VIDA</strong>.</p>

</div>
</div>
<div class="container clearfix">
<div class="one-third column right">
<h3 class="caption footer-block"><span class="bold">INFO</span> CONTACTO</h3>
		  <ul class="footer-contact-info">
			<li class="footer-loc">
			  Bv. Oro&ntilde;o 1520 <br><span class="blue">Rosario, SF, Argentina</span>
			</li>
			<li class="footer-phone">
			  (341) 424-0005
			</li>
			<li class="footer-mail">
			  <a href="mailto:info@institutocolabianchi.com">info@institutocolabianchi.com</a>
			</li>
		  </ul>
</div>
<!-- <div class="one-third column right">
<h3 class="caption footer-block">ULTIMOS <span class="bold">POSTS</span></h3>
<ul class="latest-post">
<li class="standart-post">
<h4 class="title-post-footer"><a href="blog-single.html">Donec id elit</a></h4>
<h4 class="date-post-footer">July 10, 2013</h4>
</li>
<li class="standart-post">
<h4 class="title-post-footer"><a href="blog-single.html">Donec id elit</a></h4>
<h4 class="date-post-footer">July 10, 2013</h4>
</li>
<li class="standart-post">
<h4 class="title-post-footer"><a href="blog-single.html">Donec id elit</a></h4>
<h4 class="date-post-footer">July 10, 2013</h4>
</li>
</ul>
</div> -->
</div>
</div>
<div class="footer-copyright-bg">
<div class="container ">
<div class="sixteen columns clearfix">
		  <div class="footer-menu-container">
			<nav class="clearfix" id="footer-nav">
			  <ul class="footer-menu">
				<li><a href="/">Inicio</a></li>
				<li><a href="/">El instituto</a></li>
				<li><a href="/index/servicios">Servicios</a></li>
				<li><a href="/index/fertilidad">Fertilidad</a></li>
				<li><a href="/index/avantialab">Avantia Lab</a></li>
				<li><a href="/index/contacto">Contacto</a></li>
			  </ul>
			</nav>
		  </div>	
		  <div class="footer-copyright-container right-text">
		  &copy; 2014 <a class="author" href="">institutocolabianchi.com</a> | Todos los derechos reservados
		  </div>
</div>

</div>
</div>
</footer>	
<p id="back-top">
<a href="#top" title="Back to Top"><span></span></a>
</p>
</div><!-- End wrap -->
<!-- JS begin -->
<script src="/js/jquery-2.0.3.min.js"></script>
	<script src="/ckeditor/ckeditor.js"></script>
	<script src="/js/backend/ajaxform.js"></script>
<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/js/superfish.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<!-- Flex Slider  -->
<script src="/js/jquery.flexslider.js"></script> 
<script src="/js/flex-slider.js"></script> 
<!-- end Flex Slider -->
<script type="text/javascript" src="/js/jquery.jcarousel.js"></script>
<script type="text/javascript" src="/js/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="/js/jQuery.BlackAndWhite.min.js"></script>
<script type="text/javascript" src="/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="/js/jflickrfeed.min.js"></script>
<script type="text/javascript" src="/js/jquery.quicksand.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/jquery-cookie.js"></script>  

		<!-- GOOLE MAP-->
			<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
			<script src="/js/jquery.gmap.min.js"></script>

<script type="text/javascript">
jQuery('#googlemaps').gMap({
	maptype: 'ROADMAP',
		scrollwheel: false,
		zoom: 18,
		markers: [
{
	address: 'Level 13, 2 Elizabeth St, Melbourne Victoria 3000 Australia', // Your Adress Here
		html: '',
		popup: false,
}
],
});
</script>
<script>
$('.modulo').each(function(){
	var c = this.getAttribute('rel');
	if(c == '<?= $this->modulo; ?>'){
		try{ $(this).addClass("current")} catch(e){}
	}
});
</script>
<!-- JS end -->

</body>
</html>

