
<!-- PAGE TITLE -->
	<div class="container m-bot-35 m-titles clearfix">
		<div class="sixteen columns">
			<div class="page-title-container clearfix">
				<h1 class="page-title"><span class="bold">OUPS!</span> NOT FOUND!</h1>
			</div>	
		</div>
	</div>	
	
</div>	<!-- Grey bg end -->	

<!-- 404 -->
	<div class="container m-bot-100 m-top-80 clearfix">
		<div class="eight columns ">
		
			<div class="error404-numb">
				404
			</div>
			
		</div>
		<div class="eight columns ">
		
			<div class="error404-text">
				THE PAGE<br> CANNOT<br> BE FOUND
			</div>
			
		</div>
	</div>
			
			
